version: '3.3'

services:
  server:
    container_name: warehouse
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/storagedb

    build: .
    restart: on-failure
    depends_on:
      - mysqldb

  mysqldb:
      image: mysql:5.7
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=storagedb
        - MYSQL_USER=user
        - MYSQL_PASSWORD=password